app = "cdgov1"
primary_region = "arn"

[build]
  image = "docker.io/library/caddy:alpine"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[experimental]]
  # Startar Caddy som en ren reverse/forward-proxy
  cmd = ["caddy", "reverse-proxy", "--from", ":80", "--to", "http://127.0.0.1:80"]
